---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pregatit-demo-app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pregatit-demo-app-python
      version: blue
  template:
    metadata:
      name: pregatit-demo-app-python-pod
      labels:
        app: pregatit-demo-app-python
        version: blue
    spec:
      containers:
      - name: pregatit-demo-app-python-container
        image: gbrezeanu00/pregatit-demo-app-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: pregatit-demo-app-python
#   namespace: default
# spec:
#   containers:
#     - name: pregatit-demo-app-python
#       image: gbrezeanu00/pregatit-demo-app-python:latest
#   imagePullSecrets:
#     - name: jen
---
apiVersion: v1
kind: Service 
metadata:
  name: pregatit-demo-app-python-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mentorat
  type: NodePort