---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pregatit-demo-app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pregatit-demo-app-python
      version: blue
  template:
    metadata:
      name: pregatit-demo-app-python-pod
      labels:
        app: pregatit-demo-app-python
        version: blue
    spec:
      containers:
      - name: pregatit-demo-app-python-container
        image: gbrezeanu00/pregatit-demo-app-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: pregatit-demo-app-python-svc
  labels:
    app: pregatit-demo-app-python
spec:
  selector:
    app: pregatit-demo-app-python
    version: blue
  type: NodePort
  ports:
  - nodePort: 31218
    port: 80
    targetPort: 80